version: '3.2'
services:
  db:
    image: postgres

  front:
    build: web/just_run_it
    command: python3 manage.py runserver 0.0.0.0:8000
    #volumes:
    # - type: volume
    #   source: mydata
    #   target: /just_run_it/just_run_it
    ports:
     - "8000:8000"
    depends_on:
     - db

  programs:
    build: web/programs
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: python3 manage.py runserver 0.0.0.0:9000
    ports:
      - "9000:9000"

  runner:
    build: web/runner
    command: python3 run.py

volumes:
  mydata: