version: '3.2'
services:
  db:
    image: postgres
    networks:
     - just_run_it_net

  front:
    build: web/just_run_it
    command: python3 manage.py runserver 0.0.0.0:8000
    #volumes:
    # - type: volume
    #   source: mydata
    #   target: /just_run_it/just_run_it
    ports:
     - "8000:8000"
    depends_on:
     - db
    networks:
     - just_run_it_net

  programs:
    build: web/programs
    volumes:
     - "/var/run/docker.sock:/var/run/docker.sock"
    command: python3 manage.py runserver 0.0.0.0:9000
    ports:
     - "9000:9000"
    networks:
     - just_run_it_net

#  TODO these runners require proper images (ubuntu maybe)
#  runner_c:
#    build: web/runners/runner_c
#    command: python3 run.py
#
#  runner_cpp:
#    build: web/runners/runner_cpp
#    command: python3 run.py

  runner_python:
    build: web/runners/runner_python
    command: python3 run.py

volumes:
  mydata:

networks:
  just_run_it_net:
    external: true
