version: '3.2'

services:
  front_db:
    image: postgres
    volumes:
      - "front_db:/var/lib/postgresql/data"
    networks:
     - just_run_it_net

  front:
    build: web/just_run_it
    command: python3 manage.py runserver 0.0.0.0:8000
    #volumes:
    # - type: volume
    #   source: mydata
    #   target: /just_run_it/just_run_it
    ports:
     - "8000:8000"
    depends_on:
     - front_db
    networks:
     - just_run_it_net

  programs_db:
    image: postgres
    volumes:
      - "programs_db:/var/lib/postgresql/data"
    networks:
      - just_run_it_net

  programs:
    build: web/programs
    volumes:
     - "/var/run/docker.sock:/var/run/docker.sock"
     - "program_files:/programs/files"
    command: python3 manage.py runserver 0.0.0.0:9000
    ports:
     - "9000:9000"
    depends_on:
      - programs_db
    networks:
     - just_run_it_net

  runner_c:
    build: web/runner
    command: python3 run.py C

  runner_cpp:
    build: web/runner
    command: python3 run.py CPP

  runner_python:
    build: web/runner
    command: python3 run.py PYTHON3

  message-broker:
    image: "rabbitmq:3.6.14-management"
    ports:
      - 5672:5672
      - 15672:15672
    networks:
     - just_run_it_net

volumes:
  front_db:
  programs_db:
  program_files:

networks:
  just_run_it_net:
    external: true
