# Generated by Django 2.0.6 on 2018-06-12 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100)),
                ('folderName', models.CharField(max_length=150)),
                ('timeExecuted', models.DateTimeField()),
                ('status', models.IntegerField()),
                ('language', models.CharField(max_length=10)),
            ],
        ),
    ]
