# Generated by Django 2.0.6 on 2018-06-10 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('content', models.TextField(verbose_name='Your source code')),
                ('input', models.TextField()),
                ('err_code', models.IntegerField(null=True, verbose_name='Error code of the program')),
                ('output', models.TextField(verbose_name='Written to standard output')),
                ('err_output', models.TextField(verbose_name='Written to standard error output')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author of the source code')),
            ],
        ),
    ]
