# Generated by Django 2.0.6 on 2018-06-10 18:35
from django.contrib.auth.models import User
from django.db import migrations

def add_user(apps, schema_editor):
    user = User.objects.create_user('testuser', 'testuser@gmail.com', 'jnp2docker')
    user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0002_submission_status'),
    ]

    operations = [
        migrations.RunPython(add_user,
                             reverse_code=migrations.RunPython.noop)

    ]
