# Generated by Django 2.0.6 on 2018-06-13 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0004_auto_20180611_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='input',
            field=models.TextField(blank=True),
        ),
    ]
